### ISSUE TITLE
Consider adding TypeScript support

### ISSUE THREAD

**Issue by MichalPodeszwa** [MauriceButler/bunyan-loggly#10]
Hey,
First of all, thank you for the project.

Have you considered adding typings to add support for TypeScript? Here's link to issue to help doing that.
typings/typings#322

**Comment by MauriceButler** [comment]
Hi @MichalPodeszwa 

Thanks!

As of yet no, I have not considered adding types. I personaly don't use them day to day thus have not looked into it.

If this is something you are passionate about though I am happy to merge in a change that adds support.

**Comment by bilby91** [comment]
Hello, 

I have created some typings for this. Will make a PR

**Comment by MauriceButler** [comment]
Added in v1.3.1
