### ISSUE TITLE
v1.2.0 is failing NSP security check

### ISSUE THREAD

**Issue by marin-liovic** [MauriceButler/bunyan-loggly#17]
This is failing NSP check because of a dependency it uses. More information here: https://nodesecurity.io/advisories/533
Since dependency might not get patched soon, is there a possibility to remove it from this project or use a secure one?

**Comment by MauriceButler** [comment]
Hi @marin-liovic,

~~I just released version 1.3.0 a few minutes ago which addresses this issue as per #13~~

I was incorrect the timespan issue is still present.

The downsteam issue is here https://github.com/loggly/node-loggly-bulk/issues/20

**Comment by mostlyjason** [comment]
The above issue has been fixed

**Comment by MauriceButler** [comment]
Version v1.3.2 has been published which now passes NSP check
