### ISSUE TITLE
please remove adding 'https' tag per default

### ISSUE THREAD

**Issue by Ognian** [MauriceButler/bunyan-loggly#2]
the problem is that this tag will be added even more than once, depending on how someone is using this module and that it is not possible to remove it...

**Comment by smebberson** [comment]
Yeah, that's a good point. I'll remove that.

**Comment by MauriceButler** [comment]
Hi @Ognian 

I have just taken over maintenance of this package, and I agree with your issue.

I am going to do a bit of cleanup and release a version 1.0.0 soon which will include this change

**Comment by MauriceButler** [comment]
This issue has been addressed and is available in version 1.0.0

https://github.com/MauriceButler/bunyan-loggly/commit/713619d1b0f7841377313ad76a700e0eecadfafd#diff-168726dbe96b3ce427e7fedce31bb0bcL19
