### ISSUE TITLE
No logs being received - how to troubleshoot?

### ISSUE THREAD

**Issue by Eric24** [MauriceButler/bunyan-loggly#29]
I've set up bunyan-loggly as described below (and I've tried every variation of this I could think of). I get no errors, but I also get no logs in my Loggly account. I have successfully used pm2-loggly with the same credentials (token and subdomain) and it works fine, so I feel confident in the credentials and the account configuration. How can I troubleshoot?

```
const logStreams = [];

const loggly = require('bunyan-loggly');
logStreams.push({
  type: 'raw',
  level: CONFIG.LOGGER.LOGGLY.LEVEL,
  stream: new loggly({
    token: CONFIG.LOGGER.LOGGLY.TOKEN,
    subdomain: CONFIG.LOGGER.LOGGLY.SUBDOMAIN,
    tags: CONFIG.LOGGER.LOGGLY.TAGS
  }, 10, 1000)
});

const log = require('bunyan').createLogger({
  name: 'ES',
  streams: logStreams
});
```

**Comment by MauriceButler** [comment]
Hi @Eric24,
I cant see anything in particularly wrong with you code but there was some issues around batching a while back.

If you are still having issues I can only suggest updating to the latest version and trying again.
