### ISSUE TITLE
SyntaxError: Unexpected token )

### ISSUE THREAD

**Issue by epiales** [MauriceButler/bunyan-loggly#33]
With the most recent version published (1.4.0) I am now getting an error on line 31 of index

```
/..../node_modules/bunyan-loggly/index.js:31

        );

        ^



SyntaxError: Unexpected token )
```

**Comment by rizowski** [comment]
This happens on node 6. Node 8 it doesn't show up.

**Comment by epiales** [comment]
I tested this on 6.12.2 and it threw the error, 8.12.0 did not.

**Comment by MauriceButler** [comment]
[bunyan-loggly@1.4.1](https://github.com/MauriceButler/bunyan-loggly/releases/tag/v1.4.1) has been published to resolve this.
