### ISSUE TITLE
Node version support

### ISSUE THREAD

**Issue by MauriceButler** [MauriceButler/bunyan-loggly#35]
As was brought up in #33 it seems there is still a number of people using node version 6.x

Node 6.x will go end of life in April 2019 (https://github.com/nodejs/Release#release-schedule).  

I am interested in what the user base thinks about dropping support in a major version bump.

There is no new functionality or features being relied on from newer versions, however things like trailing commas etc are built in to most editors, formatters, etc these days make it much harder to keep support for these older versions. Hence the issue introduced in #33

Also the lack of `package-lock.json` support or explicit version locking in `package.json` means that npm versions shipping with node 6 expose / exacerbate these issues and more.

I am assuming @rizowski @dncrews @stephan-nordnes-eriksen @epiales you all may have an opinion / some insight into the usage of node 6 and your migration plans?

**Comment by dncrews** [comment]
I like the idea of a major bump for that. Mostly it comes down to the platform availability, so we'll probably have stuff on 6 until AWS drops support.

**Comment by MauriceButler** [comment]
New Major version [v2.0.0](https://github.com/MauriceButler/bunyan-loggly/releases/tag/v2.0.0)
