### ISSUE TITLE
Possible incorrect interface

### ISSUE THREAD

**Issue by brendan-hurley** [MauriceButler/bunyan-loggly#36]
https://github.com/MauriceButler/bunyan-loggly/blob/d53c766c62804db8d7663ae2f0194c249002836f/index.d.ts#L5

How does this implement [bunyan.Stream](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/bunyan/index.d.ts#L224)?

I delved a little into this and found that the resultant type has no `write` member as it's supposed to either.

Perhaps it's deviated a little from the mainline bunyan type, unless someone can point out where I'm missing something?

**Comment by MauriceButler** [comment]
To be honest, I have no idea when it comes to types.

If it is still incorrect, in the latest version [v2.0.0](https://github.com/MauriceButler/bunyan-loggly/releases/tag/v2.0.0) please feel free to update it to be correct, and I will merge in your changes.
