### ISSUE TITLE
bunyan-loggly modifies the bunyan log object

### ISSUE THREAD

**Issue by santiagoaguiar** [MauriceButler/bunyan-loggly#5]
To add the `timestamp` field and remove `time`, it [modifies](https://github.com/smebberson/bunyan-loggly/blob/master/index.js#L35) the passed `log` object. 

Regrettably, this might break other configured streams (for example, it does break [bunyan-cloudwatch](https://github.com/mirkokiefer/bunyan-cloudwatch/blob/master/index.js#L117)).

Though it's of course more expensive, it should create a new object. Maybe an option could be provided to do one or the other, but IMO the right thing to do is to treat the log object as immutable, so it should default to that behavior.

**Comment by MauriceButler** [comment]
Hi @santiagoaguiar 

I have just taken over maintenance of this package, and I agree with your issue.

I am going to do a bit of cleanup and release a version 1.0.0 soon which will include this change

**Comment by MauriceButler** [comment]
This issue has been addressed and is available in version 1.0.0

https://github.com/MauriceButler/bunyan-loggly/commit/713619d1b0f7841377313ad76a700e0eecadfafd#diff-168726dbe96b3ce427e7fedce31bb0bcR23

**Comment by santiagoaguiar** [comment]
Excellent! Thanks!
