### ISSUE TITLE
Tag releases and write a changelog

### ISSUE THREAD

**Issue by voxpelli** [MauriceButler/bunyan-loggly#6]
Great to see some updates on this project, thanks!

The bump from `0.0.5` to `1.0.0` is much appreciated – but some release notes and a tag of the new release would have been welcome, so one could easily spot whether this move from `0.0.5` means that the entire API has been remade or whether one can expect at least some API-compatibility (by looking through the diff I assume the latter)

The release notes could either be placed in eg. a `CHANGELOG.md` file or as part of the tag message – or preferably both. (One can subscribe to new tags on GitHub using an RSS reader and thus get the release notes easily that way for example)

A good note on how and why etc to keep a good changelog can be found at: http://keepachangelog.com/

By making it easy for people to move to new versions one can as a maintainer ensure that one has more of ones users on ones latest versions and thus can ensure that one gets feedback on stuff that matters to push the project forward rather than having people point out either outdated errors or mishandled upgrades.

Thanks again for updating the project!

**Comment by MauriceButler** [comment]
Hi @voxpelli I have just tagged and created a github release [v1.0.0](https://github.com/MauriceButler/bunyan-loggly/releases/tag/v1.0.0)

I will do so for future releases as well. 

The bump to 1.0.0 was to get the project into line with semver and also to represent to breaking change of making the constructor exported directly.

Hopefully this give you the info you were looking for.
